export const ALL_COACH_REQUEST = "ALL_COACH_REQUEST";
export const ALL_COACH_SUCCESS = "ALL_COACH_SUCCESS";
export const ALL_COACH_FAIL = "ALL_COACH_FAIL";

export const DELETE_COACH_SUCCESS = "DELETE_COACH_SUCCESS";
export const DELETE_COACH_ERROR = "DELETE_COACH_ERROR";

export const CREATE_COACH_REQUEST = "CREATE_COACH_REQUEST";
export const CREATE_COACH_SUCCESS = "CREATE_COACH_SUCCESS";
export const CREATE_COACH_FAIL = "CREATE_COACH_FAIL";

export const SET_SELECTED_COACH = "SET_SELECTED_COACH";
export const CLEAR_SELECTED_COACH = "CLEAR_SELECTED_COACH";
