export const ALL_SPECIALIZATIONS_REQUEST = "ALL_SPECIALIZATIONS_REQUEST";
export const ALL_SPECIALIZATIONS_SUCCESS = "ALL_SPECIALIZATIONS_SUCCESS";
export const ALL_SPECIALIZATIONS_FAIL = "ALL_SPECIALIZATIONS_FAIL";
